### ISSUE TITLE
bg

### ISSUE THREAD

**Issue by fieu** [maxouloulou83/portefolio2021#1]
t tellement bg c cho j'arrive pas a dormir tellement je pense a toi
![](https://media.giphy.com/media/AVBo5eqFXd3SU/giphy.gif)

**Comment by maxouloulou83** [comment]
arrête thomas va être jaloux

**Comment by Havenstd06** [comment]
> arrête thomas va être jaloux

pfff 😒

**Comment by fieu** [comment]
> > arrête thomas va être jaloux
> 
> pfff 😒

srx ca se montre grv

**Comment by Havenstd06** [comment]
> > > arrête thomas va être jaloux
> > 
> > 
> > pfff 😒
> 
> srx ca se montre grv

...
